### ISSUE TITLE
Unhandled Response Samsung TV

### ISSUE THREAD

**Issue by monnarr** [kdschlosser/samsungctl#139]
Hello if I want to give the TV a command, I get a message on TV were I have to accept a foreign controller.
But I got this error in my command prompt
Traceback (most recent call last):
  File "C:\Program Files\Python39\Scripts\samsungctl-script.py", line 33, in <module>
    sys.exit(load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')())
  File "C:\Program Files\Python39\lib\site-packages\samsungctl-0.8.0b0-py3.9.egg\samsungctl\__main__.py", line 355, in main
    with Remote(config) as remote:
  File "C:\Program Files\Python39\lib\site-packages\samsungctl-0.8.0b0-py3.9.egg\samsungctl\remote.py", line 67, in __enter__
    self.open()
  File "C:\Program Files\Python39\lib\site-packages\samsungctl-0.8.0b0-py3.9.egg\samsungctl\utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\samsungctl-0.8.0b0-py3.9.egg\samsungctl\remote_legacy.py", line 95, in open
    self._read_response(True)
  File "C:\Program Files\Python39\lib\site-packages\samsungctl-0.8.0b0-py3.9.egg\samsungctl\utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\samsungctl-0.8.0b0-py3.9.egg\samsungctl\remote_legacy.py", line 156, in _read_response
    raise exceptions.UnhandledResponse(response)
samsungctl.exceptions.UnhandledResponse: <exception str() failed>

Can someone help?

**Comment by ToasterDEV** [comment]
I can attest to having the exact same issue, here is my traceback:

```
$ samsungctl --host 192.168.1.7 --name myremote KEY_VOLDOWN
Traceback (most recent call last):
  File "/home/toasterdev/miniconda3/bin/samsungctl", line 33, in <module>
    sys.exit(load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')())
  File "/home/toasterdev/miniconda3/lib/python3.9/site-packages/samsungctl-0.8.0b0-py3.9.egg/samsungctl/__main__.py", line 355, in main
    with Remote(config) as remote:
  File "/home/toasterdev/miniconda3/lib/python3.9/site-packages/samsungctl-0.8.0b0-py3.9.egg/samsungctl/remote.py", line 67, in __enter__
    self.open()
  File "/home/toasterdev/miniconda3/lib/python3.9/site-packages/samsungctl-0.8.0b0-py3.9.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/toasterdev/miniconda3/lib/python3.9/site-packages/samsungctl-0.8.0b0-py3.9.egg/samsungctl/remote_legacy.py", line 95, in open
    self._read_response(True)
  File "/home/toasterdev/miniconda3/lib/python3.9/site-packages/samsungctl-0.8.0b0-py3.9.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/toasterdev/miniconda3/lib/python3.9/site-packages/samsungctl-0.8.0b0-py3.9.egg/samsungctl/remote_legacy.py", line 156, in _read_response
    raise exceptions.UnhandledResponse(response)
samsungctl.exceptions.UnhandledResponse: <exception str() failed>
```

The TV prompts for permission to allow "myremote" to control it, but after that nothing happens.

Thanks for the help!
