### ISSUE TITLE
Samsungctl connection failure/refused (with logs)

### ISSUE THREAD

**Issue by arsaboo** [kdschlosser/samsungctl#23]
So, I decided to do a clean install of `samsungctl` using the `combination_branch`, but I am seeing similar errors (on my NU8000). Here are the logs:
```
pi@raspberrypi:~/samsungctl $ samsungctl --host 192.168.2.252
Traceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/__main__.py", line 181, in main
    with Remote(config) as remote:
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote.py", line 11, in __init__
    self.remote = RemoteLegacy(config)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote_legacy.py", line 27, in __init__
    self.connection.connect((config["host"], config["port"]))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
pi@raspberrypi:~/samsungctl $ samsungctl --host 192.168.2.252 --method websocket
Traceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/__main__.py", line 181, in main
    with Remote(config) as remote:
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote.py", line 13, in __init__
    self.remote = RemoteWebsocket(config)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote_websocket.py", line 65, in __init__
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote_websocket.py", line 132, in open
    raise RuntimeError('Connection Failure')
RuntimeError: Connection Failure
pi@raspberrypi:~/samsungctl $ samsungctl --host 192.168.2.252 --method websocket --port 8001
Traceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/__main__.py", line 181, in main
    with Remote(config) as remote:
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote.py", line 13, in __init__
    self.remote = RemoteWebsocket(config)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote_websocket.py", line 65, in __init__
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote_websocket.py", line 132, in open
    raise RuntimeError('Connection Failure')
RuntimeError: Connection Failure
```

Please let me know if you would like me to test anything. Hope we can resolve this.

**Comment by arsaboo** [comment]
Ok...that seems to have worked. 
`samsungctl --host 192.168.2.252 --method websocket --port 8002 --name remoteCmd KEY_VOLDOWN` reduced the volume. Let me test some more.

**Comment by kdschlosser** [comment]
if you add -vvvv to your command line arguments it will go into debugging mode and it will give me a whole lot more information as to where a problem can be coming from.

**Comment by kdschlosser** [comment]
I will lock down the problem. it's just that all of the people posting conflicting information was making me coo coo. we need to address on issue at a time and in order and in a separate thread for each issue. this way I do not get things all jumbled up. Github has a nasty thing that it does when a thread gets to long and it collapses the posts. it is very easy to miss something someone may have said when it does this.

I will key out a script you can run that will roll through all of the different features this way we know if things are working or not.

**Comment by arsaboo** [comment]
It returned nothing

```
pi@raspberrypi:~/samsungctl $ samsungctl --host 192.168.2.252 --method websocket --port 8002 --name remoteCmd KEY_VOLDOWN -vvvv
pi@raspberrypi:~/samsungctl $
```

**Comment by kdschlosser** [comment]
-vvvv before the actual remote key you want to press.

**Comment by kdschlosser** [comment]
samsungctl -vvvv --host 192.168.2.252 --method websocket --port 8002 --name remoteCmd KEY_VOLDOWN

**Comment by arsaboo** [comment]
still nothing 
```
pi@raspberrypi:~/samsungctl $ samsungctl -vvvv --host 192.168.2.252 --method websocket --port 8002 --name remoteCmd KEY_VOLDOWN
pi@raspberrypi:~/samsungctl $
```

**Comment by arsaboo** [comment]
ok...time to hit the bed now. But, if you get the script ready, I should be able to run it and give you the output.

**Comment by kdschlosser** [comment]
my question is tho. is it functioning even tho ther is no debug output. (could be a bug I have to fix.)

**Comment by arsaboo** [comment]
yes, it is functioning without the debug output. I was able to lower the volume.

**Comment by arsaboo** [comment]
Tried the `updates_logging` branch with the same command, but still not additional logs.
