### ISSUE TITLE
setup.py not working :)

### ISSUE THREAD

**Issue by matthieut59** [kdschlosser/samsungctl#33]
Hello,

When doing setup.py install, I got 👍 

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import samsungctl # NOQA
  File "C:\Users\mtourlouse\samsung\samsungctl\__init__.py", line 24, in <module>
    from .remote import Remote # NOQA
  File "C:\Users\mtourlouse\samsung\samsungctl\remote.py", line 5, in <module>
    from .remote_websocket import RemoteWebsocket
  File "C:\Users\mtourlouse\samsung\samsungctl\remote_websocket.py", line 14, in <module>
    from . import application
  File "C:\Users\mtourlouse\samsung\samsungctl\application.py", line 8, in <module>
    class Application(object):
  File "C:\Users\mtourlouse\samsung\samsungctl\application.py", line 28, in Application
    mbrSource=None
  File "C:\Users\mtourlouse\samsung\samsungctl\utils.py", line 15, in LogIt
    if func.func_code.co_flags & 0x20:
AttributeError: 'function' object has no attribute 'func_code'

Fix on my side was to fully comment LogIt function, but I guess it s not a proper fix :)

Can you have a look ?

Thks,

matt

**Comment by kdschlosser** [comment]
woopsie. I forgot they changed the func_code to code in python 3

**Comment by kdschlosser** [comment]
it is fixed.

**Comment by matthieut59** [comment]
working thks!
