### ISSUE TITLE
issue with zip function

### ISSUE THREAD

**Issue by matthieut59** [kdschlosser/samsungctl#34]
Hello again,

probably another python 3 issue ;)
λ samsungctl --host 192.168.1.7 --name myremote --method websocket --port 8002 KEY_POWERON                                                                                      
Traceback (most recent call last):                                                                                                                                              
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\Scripts\samsungctl-script.py", line 11, in <module>                                                       
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()                                                                                                  
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\__main__.py", line 242, in main                 
    with Remote(config, log_level) as remote:                                                                                                                                   
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 20, in __init__                
    self.remote = RemoteWebsocket(config)                                                                                                                                       
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\utils.py", line 25, in wrapper                  
    func_name, arg_string = func_arg_string(func, args, kwargs)                                                                                                                 
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\utils.py", line 69, in func_arg_string          
    for key, value in zip(arg_names, args)[start:]:                                                                                                                             
TypeError: 'zip' object is not subscriptable                                                                                                                                    

Probably linked to this https://stackoverflow.com/questions/27431390/typeerror-zip-object-is-not-subscriptable

Can you have a look ?

Sorry for this other one ;)

Thks,

matt

**Comment by AidasK** [comment]
same:
```
root@hassbian:~/samsungctl# python3 -m samsungctl --host 192.168.8.102 --method websocket --port 8001 --name remoteCmd KEY_VOLDOWN -vvvv
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/samsungctl/samsungctl/__main__.py", line 274, in <module>
    main()
  File "/root/samsungctl/samsungctl/__main__.py", line 242, in main
    with Remote(config, log_level) as remote:
  File "/root/samsungctl/samsungctl/remote.py", line 20, in __init__
    self.remote = RemoteWebsocket(config)
  File "/root/samsungctl/samsungctl/utils.py", line 25, in wrapper
    func_name, arg_string = func_arg_string(func, args, kwargs)
  File "/root/samsungctl/samsungctl/utils.py", line 69, in func_arg_string
    for key, value in zip(arg_names, args)[start:]:
TypeError: 'zip' object is not subscriptable
```

**Comment by AidasK** [comment]
Works with python 2.7

**Comment by matthieut59** [comment]
for key, value in list(zip(arg_names, args))[start:]: -> fixed the issue at line #69

**Comment by kdschlosser** [comment]
@matthieut59

if that is the fix for this issue can you submit a PR against the master branch for it please :smile:

**Comment by AlexStapleton** [comment]
I edited the utils.py to include the List() component but it still sent me the same error "TypeError: 'zip' object is not subscriptable"

Not sure if I'm doing something wrong or not, but this might need some additional testing.

**Comment by kdschlosser** [comment]
you have to make sure that you are not wrapping the whole function call with list(). I know there is a string slice at the end. this needs to be outside the ()'s 

this is wrong

    list(zip(arg_names, args)[start:])

this is right

    list(zip(arg_names, args))[start:]
