### ISSUE TITLE
EU75NU7172 ValueError: invalid literal for int() with base 16: b''

### ISSUE THREAD

**Issue by AidasK** [kdschlosser/samsungctl#35]
Does not work with EU75NU7172:
```
root@hassbian:~/samsungctl# python3 -m samsungctl --host 192.168.8.102 --port 8001
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/samsungctl/samsungctl/__main__.py", line 274, in <module>
    main()
  File "/root/samsungctl/samsungctl/__main__.py", line 242, in main
    with Remote(config, log_level) as remote:
  File "/root/samsungctl/samsungctl/remote.py", line 18, in __init__
    self.remote = RemoteLegacy(config)
  File "/root/samsungctl/samsungctl/remote_legacy.py", line 39, in __init__
    self._read_response(True)
  File "/root/samsungctl/samsungctl/remote_legacy.py", line 77, in _read_response
    response_len = int(codecs.encode(self.connection.recv(2), 'hex'), 16)
ValueError: invalid literal for int() with base 16: b''
```

**Comment by AidasK** [comment]
Works with python 2.7

**Comment by kdschlosser** [comment]
You are running a new TV. you need to add 

    --method websocket

to the command line.
