### ISSUE TITLE
Unable to control legacy TV - invalid literal for int() with base 16

### ISSUE THREAD

**Issue by jnimmo** [kdschlosser/samsungctl#41]
Appear to be running into invalid literal with the read_response method for remote_legacy
This is on an old 32" running firmware 1012
`(homeassistant) homeassistant@hass:~/UPNP_Device/UPNP_Device$ samsungctl --host 192.168.2.33 --name 'Samsung TV Remote' KEY_HDMI -vvvv
Sending handshake.
Connected to 'iapp.samsungd'.
Traceback (most recent call last):
  File "/srv/homeassistant/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/srv/homeassistant/lib/python3.5/site-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/__main__.py", line 242, in main
    with Remote(config, log_level) as remote:
  File "/srv/homeassistant/lib/python3.5/site-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/remote.py", line 18, in __init__
    self.remote = RemoteLegacy(config)
  File "/srv/homeassistant/lib/python3.5/site-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/remote_legacy.py", line 41, in __init__
    self._read_response(True)
  File "/srv/homeassistant/lib/python3.5/site-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/remote_legacy.py", line 82, in _read_response
    response_len = int(codecs.encode(self.connection.recv(2), 'hex'), 16)
ValueError: invalid literal for int() with base 16: b''
(homeassistant) homeassistant@hass:~/UPNP_Device/UPNP_Device$
`

I'll try and look into it but documenting here for a start

**Comment by kdschlosser** [comment]
The library is getting a response of an empty string. It is talking to your TV but the TV is responding with nothing.

I will look into it when I get home. I have a UN55D8000 which is legacy. So I will test it and see what happens.

**Comment by kdschlosser** [comment]
what is the model number of your TV?
