### ISSUE TITLE
It broke after some time of using with home assistant py35

### ISSUE THREAD

**Issue by AidasK** [kdschlosser/samsungctl#44]
Worked a few times, but then I saw this in the log:
```
2019-01-18 20:24:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/service.py", line 286, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/media_player/samsungtv.py", line 207, in turn_off
    self.send_key('KEY_POWER')
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/media_player/samsungtv.py", line 151, in send_key
    self.get_remote().control(key)
  File "/srv/homeassistant/lib/python3.5/site-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/remote.py", line 29, in control
    return self.remote.control(key)
  File "/srv/homeassistant/lib/python3.5/site-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/utils.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/remote_websocket.py", line 322, in control
    self.power = True
  File "/srv/homeassistant/lib/python3.5/site-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/utils.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/remote_websocket.py", line 96, in power
    wake_on_lan.send_wol(self.mac_address)
  File "/srv/homeassistant/lib/python3.5/site-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/wake_on_lan.py", line 239, in send_wol
    packet = '\xff' * 6 + hex_mac * 16
TypeError: Can't convert 'bytes' object to str implicitly

```

**Comment by AidasK** [comment]
mac address I am using: 9C:8C:6E:D7:7A:51

**Comment by AidasK** [comment]
fixed by changing this line:
https://github.com/kdschlosser/samsungctl/blob/master/samsungctl/wake_on_lan.py#L239
```
    packet = '\xff' * 6 + hex_mac * 16
```
to
```
    packet = b'\xff' * 6 + hex_mac * 16
```

**Comment by AidasK** [comment]
feel free to make a pull request with this fix

**Comment by kdschlosser** [comment]
Yes please. A PR would be most helpful
