### ISSUE TITLE
Unexpected keyword argument 'key'

### ISSUE THREAD

**Issue by polcape** [kdschlosser/samsungctl#48]
With the last version of library I try to run this 

`python -m samsungctl --host 192.168.1.110 KEY_VOLDOWN`

and obtain this response

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/paolo/Workspace/samsungctl/samsungctl/__main__.py", line 282, in <module>
    main()
  File "/home/paolo/Workspace/samsungctl/samsungctl/__main__.py", line 247, in main
    config = Config(**config)
TypeError: __init__() got an unexpected keyword argument 'key'
```

Whatever command I send obtain this response

**Comment by dennismenken** [comment]
Hello guys,

I got the same error. I tried also to put the config files in .config and in /etc.

Best regards,
Dennis

**Comment by kdschlosser** [comment]
OK no worries. It's funny I was just looking at the code.. and said to myself, there might be a bug here..

**Comment by kdschlosser** [comment]
fixed
