### ISSUE TITLE
New UPNP Changes Seem to Break Auth - RuntimeError: Auth Failure

### ISSUE THREAD

**Issue by mikelitka** [kdschlosser/samsungctl#60]
[root@localhost bin]# python3.6 samsungctl --host 10.99.1.139 --method websocket --config-file ~/tv-living-room.conf
Traceback (most recent call last):
  File "samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/__main__.py", line 345, in main
    with Remote(config) as remote:
  File "/usr/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote.py", line 69, in __enter__
    self.open()
  File "/usr/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote.py", line 76, in open
    self.remote.open()
  File "/usr/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote_websocket.py", line 255, in open
    raise RuntimeError('Auth Failure')
RuntimeError: Auth Failure

**Comment by matthieut59** [comment]
Mine still working, have you tried to delete and recreate config using rhe load and save method recently introduced?

**Comment by kdschlosser** [comment]
remove any remote pairing from the TV that you may have on the TV..

and see if it will then work

**Comment by kdschlosser** [comment]
also as a suggestion. always surround any path statements sent to a command line interface with double quotes.

    samsungctl --host 10.99.1.139 --method websocket --config-file "~/tv-living-room.conf"

this will ensure that the argument parser doesn't cut something up thinking it is a different argument.

**Comment by mikelitka** [comment]
Tried both of those suggestions. And it is still throwing Auth Errors. I have tried two different VMs as well. Going to do a packet capture and see what is happening.

**Comment by kdschlosser** [comment]
it should be doing that automatically if you specify only the method and not the port. this will default the connection to port 8001. and if there is an auth failure then the connection should flip over to 8002. 

Unless there is some other response that is being generated by the TV when this happens.

So if you can do me a favor.. reopen this issue because it is a problem in the library..

lets see what kind of debugging we can get on the data that comes in from the TV.

    samsungctl --host 10.99.1.139 --method websocket -vvvv KEY_MENU

give that a go and see what happens.
if you can paste the output here that would be most helpful.

**Comment by mikelitka** [comment]
[root@localhost samsungctl]# samsungctl --host 10.99.1.139 --method websocket -vvvv KEY_MENU
Websocket closed
Traceback (most recent call last):
  File "/usr/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/__main__.py", line 345, in main
    with Remote(config) as remote:
  File "/usr/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote.py", line 69, in __enter__
    self.open()
  File "/usr/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote.py", line 76, in open
    self.remote.open()
  File "/usr/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote_websocket.py", line 255, in open
    raise RuntimeError('Auth Failure')
RuntimeError: Auth Failure

**Comment by kdschlosser** [comment]
I added a print statement to see if there is any kind of data that is spat back out the connection.
reinstall the library cloning the master branch. and run that same command again.

**Comment by mikelitka** [comment]
Nothing different. 
Attaching packet capture.

[tv.cap.zip](https://github.com/kdschlosser/samsungctl/files/2799322/tv.cap.zip)
