### ISSUE TITLE
RuntimeError: Python 2 is not currently supported for H and J model year TV's

### ISSUE THREAD

**Issue by andreas-bulling** [kdschlosser/samsungctl#64]
But the user has no choice to run the "binary" in /usr/local/bin with python3 as python2 is hardcoded

```
samsungctl --host 192.168.178.60 --port 8080 --method encrypted
Traceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/local/lib/python2.7/site-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/__main__.py", line 345, in main
    with Remote(config) as remote:
  File "/usr/local/lib/python2.7/site-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote.py", line 33, in __init__
    'Python 2 is not currently supported '
RuntimeError: Python 2 is not currently supported for H and J model year TV's
```

**Comment by kdschlosser** [comment]
Yeah ok...

did you read the error??
