### ISSUE TITLE
remote.connect_upnp() still crashing (bis)

### ISSUE THREAD

**Issue by matthieut59** [kdschlosser/samsungctl#67]
Hello,

same code as your example
config = samsungctl.Config(
name='samsungctl',
description='samsungctl-library',
method='websocket',
host='192.168.1.7',
port=8002
)

config.log_level = logging.DEBUG
#config.save("C:\Users\mtourlouse\")
config = samsungctl.Config.load("C:\Users\mtourlouse\samsungctl.config")

with samsungctl.Remote(config) as remote:
remote.connect_upnp()
print(remote.upnp_tv.as_dict)

Got this error like hundreds of time before it stops (line 42, line 95, line 42, line95 etc.) :

File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 95, in getattr
self.connect_upnp()
File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 42, in connect_upnp
if self._upnp is None:
File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 95, in getattr
self.connect_upnp()
File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 42, in connect_upnp
if self._upnp is None:
File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 95, in getattr
self.connect_upnp()
File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 42, in connect_upnp
if self._upnp is None:
File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 81, in getattr
if hasattr(self.remote, item):
RecursionError: maximum recursion depth exceeded while calling a Python object

Good luck again, your last fix on remote.py ( __setattr__) did not solve the issue.

Thks!

**Comment by matthieut59** [comment]
Same output 👍 
C:\Users\mtourlouse                                                                                                                                                        
λ python debugsamsung.py                                                                                                                                                   
using saved token: 16339238                                                                                                                                                
incoming message: {"data":{"clients":[{"attributes":{"name":"c2Ftc3VuZ2N0bA==","token":"16339238"},"connectTime":1548601768527,"deviceName":"c2Ftc3VuZ2N0bA==","id":"2b8321
76-edf7-40d5-80de-8811c8fd8c23","isHost":false}],"id":"2b832176-edf7-40d5-80de-8811c8fd8c23"},"event":"ms.channel.connect"}                                                
                                                                                                                                                                           
Access granted.                                                                                                                                                            
Access granted.                                                                                                                                                            
Websocket closed                                                                                                                                                           
Traceback (most recent call last):                                                                                                                                         
  File "debugsamsung.py", line 64, in <module>                                                                                                                             
    remote.connect_upnp()                                                                                                                                                  
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 42, in connect_upnp       
    if self._upnp is None:                                                                                                                                                 
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 95, in __getattr__        
    self.connect_upnp()                                                                                                                                                    
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 42, in connect_upnp       
    if self._upnp is None:                                                                                                                                                 
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 95, in __getattr__        

loopin on those 2 errors until : 

  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 42, in connect_upnp
    if self._upnp is None:
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 81, in __getattr__
    if hasattr(self.remote, item):
RecursionError: maximum recursion depth exceeded while calling a Python object

Sorry If I m useless here :/

**Comment by kdschlosser** [comment]
heh.. You have something wrong. it is not updating..
There is no getattr anymore. so the output could not possibly be the same.

line 81 in the error above shows "if hasattr(self.remote, item)

well line 81 is actually "self.config = config"

**Comment by matthieut59** [comment]
My bad,  my last pull from your repo failed, so now I have : 

λ python debugsamsung.py                                                                                                                                                   
using saved token: 16339238                                                                                                                                                
incoming message: {"data":{"clients":[{"attributes":{"name":"c2Ftc3VuZ2N0bA==","token":"16339238"},"connectTime":1548617774063,"deviceName":"c2Ftc3VuZ2N0bA==","id":"86b972
e5-45a7-4390-85eb-eee6f2f9c0a8","isHost":false}],"id":"86b972e5-45a7-4390-85eb-eee6f2f9c0a8"},"event":"ms.channel.connect"}                                                
                                                                                                                                                                           
Access granted.                                                                                                                                                            
Access granted.                                                                                                                                                            
Websocket closed                                                                                                                                                           
Traceback (most recent call last):                                                                                                                                         
  File "debugsamsung.py", line 64, in <module>                                                                                                                             
    remote.connect_upnp()                                                                                                                                                  
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\upnp\UPNP_Device\upnp_class.py", line 128, 
in __getattr__                                                                                                                                                             
    if item in self.__devices:                                                                                                                                             
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\upnp\UPNP_Device\upnp_class.py", line 128, 
in __getattr__                                                                                                                                                             
    if item in self.__devices:                                                                                                                                             
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\upnp\UPNP_Device\upnp_class.py", line 128, 
in __getattr__                                                                                                                                                             
    if item in self.__devices:                                                                                                                                             
  [Previous line repeated 496 more times]                                                                                                                                  
RecursionError: maximum recursion depth exceeded

**Comment by kdschlosser** [comment]
OK cool.. I will work around the getattr issue. the output is now what it is expected to be.

**Comment by matthieut59** [comment]
jsut for info using this discovery : 
https://github.com/tenable/upnp_info

Is properly retrieving the TV, So I m sure discovery is working :)

**Comment by kdschlosser** [comment]
Ok. I just have to get past the issue with getattr I will hook my TV up at home so I have a TV to test against instead of the back and forth thing on here. I am not home at the moment it will be an hour before I get home. Then I have to do a couple of things around the house. I will be able to work on. This in about 3 hours or so.

**Comment by matthieut59** [comment]
can t wait for it to work :D 
btw i m using connect_upnp method, but can t find it anywhere in the source code is it normal ?

**Comment by kdschlosser** [comment]
you do not need to use connect_upnp any more. I removed it. I am sub classing the UPNPTV class if there is location information for the TV found during the SSDP discovery routine.

I still have not had a chance to fix the issue with the getattr so be patient. I will let you know what I have repaired it.

**Comment by matthieut59** [comment]
I ll be :)
