### ISSUE TITLE
esc = r'\(' + re.escape(ip) + r'\)\s+at\s+' TypeError: must be str, not bytes

### ISSUE THREAD

**Issue by d2hf** [kdschlosser/samsungctl#74]
```
import samsungctl

config = samsungctl.Config(
    name='samsungctl',
    descriptio= 'PC',
    method='websocket',
    host='192.16.254.128',
    port=8001
)
with samsungctl.Remote(config) as remote:
    for i in range(10):
        remote.control("KEY_MENU")
        time.sleep(0.5)

```
I tried using port 8001 and 8002

Traceback (most recent call last):
  File "/Users/douglas/Desktop/tv_Test.py", line 10, in <module>
    with samsungctl.Remote(config) as remote:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote.py", line 74, in __call__
    return RemoteWrapper(conf)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote.py", line 72, in __init__
    self.open()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote_websocket.py", line 151, in open
    self.power = True
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote_websocket.py", line 86, in power
    if self.mac_address:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/utils.py", line 44, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote_websocket.py", line 44, in mac_address
    _mac_address = wake_on_lan.get_mac_address(self.config.host)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/wake_on_lan.py", line 171, in get_mac_address
    esc = r'\(' + re.escape(ip) + r'\)\s+at\s+'
TypeError: must be str, not bytes

**Comment by kdschlosser** [comment]
OK fixed one thing in the WOL and broke another. LOL
