### ISSUE TITLE
AttributeError: 'property' object has no attribute '__code__'

### ISSUE THREAD

**Issue by d2hf** [kdschlosser/samsungctl#77]
I am really trying to figure it out, but I don't understand what is going on...

Traceback (most recent call last):
  File "/Users/douglas/Desktop/tv_Test.py", line 1, in <module>
    import samsungctl
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/__init__.py", line 20, in <module>
    from .remote import Remote # NOQA
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote.py", line 13, in <module>
    from .remote_encrypted import RemoteEncrypted
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote_encrypted/__init__.py", line 34, in <module>
    class URL(object):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/remote_encrypted/__init__.py", line 48, in URL
    @property
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/samsungctl-0.8.0b0-py3.6.egg/samsungctl/utils.py", line 35, in LogItWithReturn
    if func.__code__.co_flags & 0x20:
AttributeError: 'property' object has no attribute '__code__'

**Comment by matthieut59** [comment]
was going to report the same : 

C:\Users\mtourlouse                                                                                                                                                                           
λ samsungctl --host 192.168.1.7 --volume -1 --method websocket                                                                                                                                
Traceback (most recent call last):                                                                                                                                                            
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\Scripts\samsungctl-script.py", line 11, in <module>                                                                     
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()                                                                                                                
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point                                             
    return get_distribution(dist).load_entry_point(group, name)                                                                                                                               
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point                                            
    return ep.load()                                                                                                                                                                          
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 2324, in load                                                        
    return self.resolve()                                                                                                                                                                     
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve                                                     
    module = __import__(self.module_name, fromlist=['__name__'], level=0)                                                                                                                     
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\__init__.py", line 20, in <module>                            
    from .remote import Remote # NOQA                                                                                                                                                         
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote.py", line 13, in <module>                              
    from .remote_encrypted import RemoteEncrypted                                                                                                                                             
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote_encrypted\__init__.py", line 34, in <module>           
    class URL(object):                                                                                                                                                                        
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\remote_encrypted\__init__.py", line 48, in URL                
    @property                                                                                                                                                                                 
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\utils.py", line 35, in LogItWithReturn                        
    if func.__code__.co_flags & 0x20:                                                                                                                                                         
AttributeError: 'property' object has no attribute '__code__'

**Comment by matthieut59** [comment]
final issue is 
AttributeError: 'property' object has no attribute' \_\_code\_\_' 

an not 'code' in bold but code with double underscore (git is using double underscore to put bold...)

**Comment by kdschlosser** [comment]
ok look. here is a screen shot of the code.

![image](https://user-images.githubusercontent.com/10932297/51924602-8daf5000-23aa-11e9-8f24-15e494764f6e.png)

Now specifically look at the last few lines in the traceback.

```python
File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\utils.py", line 35, in LogItWithReturn
if func.code.co_flags & 0x20:
AttributeError: 'property' object has no attribute 'code'
```

it states line 35..
and it also states that line 35 has this code

    if func.code.co_flags & 0x20:

now look at line 35 in the screen shot....

a property is a function. so it will have an `__code__` object if you are running Python 3
and it will have a `code` object if running python 2. all  functions have these objects.

if you want to test that you can by running the script below

```python

def some_test():
    pass

print(some_test.__code__)

# this next one will fail if running python 3
print(some_test.code)
```

**Comment by kdschlosser** [comment]
also take a look in the utils.py file in the repo. you will see that the code in that file is identical to what my screen shot is showing.

**Comment by kdschlosser** [comment]
crap! You are right... i missed the bold. I just saw your post about the bold thing.

OK so from now on when powting any ling of an error pleasee please please wrap all output with

\`\`\`python
\`\`\`

those are back ticks key just above the tab on a US 101 enhanced.

**Comment by kdschlosser** [comment]
I am sorry about that guys. I missed that. It is now fixed. I will remember to pay more attetion to the posted output and if an item is in bold.
