### ISSUE TITLE
Back to recursive loop on GetAttr

### ISSUE THREAD

**Issue by matthieut59** [kdschlosser/samsungctl#78]
```python
C:\Users\mtourlouse
λ samsungctl --host 192.168.1.7 --volume -1 --method websocket
Traceback (most recent call last):
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\Scripts\samsungctl-script.py", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\__main__.py", line 357, in main
    print('Volume:', remote.volume, '%')
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\upnp\__init__.py", line 791, in volume
    current_volume = self.MainTVAgent2.GetVolume()[1]
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\upnp\UPNP_Device\upnp_class.py", line 127, in __getattr__
    if item in self._devices:
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\upnp\UPNP_Device\upnp_class.py", line 127, in __getattr__
    if item in self._devices:
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\samsungctl-0.8.0b0-py3.7.egg\samsungctl\upnp\UPNP_Device\upnp_class.py", line 127, in __getattr__
    if item in self._devices:
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded

**Comment by kdschlosser** [comment]
ok I just got the unittests back up and running. lets see what happens.

**Comment by matthieut59** [comment]
Some new with last comitt, I stopped doing in on my laptop as the discovery feature is not allowed (company policy), doing it on my raspberry, I m progressing, here is the last issue (even if when discovery not working it should not crash with recursion depth ^^ )

```python
osmc@jarvis:~/Scripts-python$ samsungctl --host 192.168.1.7 --volume -1 --method websocket
['http://192.168.1.7:9119/screen_sharing', 'http://192.168.1.7:9080', 'http://192.168.1.7:9110/ip_control', 'http://192.168.1.7:9197/dmr', 'http://192.168.1.7:7678/nservice/']
Traceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/local/lib/python3.5/dist-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/__main__.py", line 341, in main
    with Remote(config) as remote:
  File "/usr/local/lib/python3.5/dist-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/remote.py", line 84, in __call__
    return RemoteWrapper(conf)
  File "/usr/local/lib/python3.5/dist-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/remote.py", line 71, in __init__
    self
  File "/usr/local/lib/python3.5/dist-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/upnp/__init__.py", line 20, in __init__
    UPNPObject.__init__(self, ip, locations)
  File "/usr/local/lib/python3.5/dist-packages/samsungctl-0.8.0b0-py3.5.egg/samsungctl/upnp/UPNP_Device/upnp_class.py", line 64, in __init__
    root = etree.fromstring(response.content)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79003)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118334)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117014)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111258)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```

With thi ocmmand : samsungctl --host 192.168.1.7 --volume -1 --method websocket

Any way to target the proper port / control without the need for a full discovery ?

**Comment by kdschlosser** [comment]
OK when you are specifying the IP address a "full discovery" is not really taking place. Yes we are sending a broadcast SSDP discovery packet. but we are only going to return t the locations where the IP that returned the reply is the same as the IP supplied.

the UPNP portion of the library is actually another library that I wrote called UPNP_Device. and thiis library is not keyed to one specific device or type of device or device manufacturer. it is designed to handle all UPNP devices. and some of those devices will only respond to a direct SSDP packet and not a broadcast one.
as from the above error we have discovered that the Samsung TV's also respond to a direct query. and the location in your case of that direct query is. http://192.168.1.7:9080. if you look that port differs from all of the rest of the locations http://192.168.1.7:9119. why is the big ? so if you key http://192.168.1.7:9080 into your web browser and after the page loads (if not an error) right click on the page and click on view as source.. then copy and paste that source into a reply to me. I will be able to see what is going on. 

I know that the information at that port is not XML. hence the error you got. I am curious to know what the information actually is. It may have some useful information.

I will code in a fix for the above.

If you do not want  to keep on going through an SSDP discovery process the way to go about it is to use --config-file and specify a file. it will do a discovery and then save the data to that file once you specify that file in repeated calls to samsungctl the whole UPNP discovery process is bypassed. because it saves the UPNP locations to the config file when you specified the file for the first time.

**Comment by kdschlosser** [comment]
ok give this a shot again. I updated the code to catch the error

**Comment by matthieut59** [comment]
You know what ? Everything is working perfectly on my raspberry now!!
the --volume -1 is working perfectly, any chance to get all media information currently playing implemented soon ?

**Comment by kdschlosser** [comment]
describe what you mean by media information...
