### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by andreas-bulling** [kdschlosser/samsungctl#85]
```
python3 -m samsungctl --host 192.168.178.60 --method encrypted                                                                          (master)
['http://192.168.178.60:7677/MainTVServer2/', 'http://192.168.178.60:7676/rcr/', 'http://192.168.178.60:9197/dmr', 'http://192.168.178.60:7678/nservice/']
Please enter pin from tv: 2761
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/andreas/Desktop/samsungctl/samsungctl/__main__.py", line 429, in <module>
    main()
  File "/Users/andreas/Desktop/samsungctl/samsungctl/__main__.py", line 341, in main
    with Remote(config) as remote:
  File "/Users/andreas/Desktop/samsungctl/samsungctl/remote.py", line 78, in __enter__
    self.open()
  File "/Users/andreas/Desktop/samsungctl/samsungctl/utils.py", line 44, in wrapper
    result = func(*args, **kwargs)
  File "/Users/andreas/Desktop/samsungctl/samsungctl/remote_encrypted/__init__.py", line 164, in open
    output = self.hello_exchange(tv_pin)
  File "/Users/andreas/Desktop/samsungctl/samsungctl/utils.py", line 44, in wrapper
    result = func(*args, **kwargs)
  File "/Users/andreas/Desktop/samsungctl/samsungctl/remote_encrypted/__init__.py", line 260, in hello_exchange
    client_hello = auth_data['GeneratorClientHello']
TypeError: string indices must be integers
```

**Comment by andreas-bulling** [comment]
ok, let me know once I should test something again

**Comment by kdschlosser** [comment]
we are almost there

**Comment by p3g4asus** [comment]
This has been fixed after merging with my encrypted_fix branch

**Comment by kdschlosser** [comment]
I am pretty sure it is as well. Just want to make sure that all is good by the user that posted the problem,

**Comment by andreas-bulling** [comment]
yes, fixed
